apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring 
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
  - name: api
    port: 9999
    targetPort: 9999
    nodePort: 30001
  - name: gui
    port: 8086
    targetPort: 8086
    nodePort: 30002
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: monitoring   
spec:
  serviceName: "influxdb"
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccount: cthulhu
      volumes:
        - name: influxdb-data
          hostPath:
            path: /root/.influxdbv2 
      containers:
      - name: influxdb
        image: quay.io/influxdb/influxdb:v2.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: 1
        ports:
        - name: api
          containerPort: 9999
        - name: gui
          containerPort: 8086
        volumeMounts:
        - name: influxdb-data
          mountPath: /root/.influxdbv2